services:
  - type: web
    name: IsraCV_Blazor
    runtime: docker
    dockerfilePath: IsraCVBlazor/Dockerfile
    startCommand: dotnet /app/IsraCVBlazor.dll
    envVars:
      - key: ASPNETCORE_URLS
        value: "http://+:8080"
      - key: PORT
        value: "8080"
    plan: free
